[package]
name = "grpc"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.14.2"
prost = "0.14.1"
tokio = { version = "1", features = ["full"] }
tonic-prost = "0.14.2"

[build-dependencies]
tonic-build = "0.14.2"
tonic-prost-build = "0.14.2"
